use_frameworks!

platform :ios, '8.0'

target 'test20200310_Example' do
  pod 'test20200310', :path => '../'

  target 'test20200310_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
